"""Fixture seeder CLI.

Subcommands:
    list                   - print all scenarios in the registry
    dry-run [--scen CODE]  - run the seeder inside a transaction and roll back
    apply   --confirm TOKEN [--scen CODE]
                           - run the seeder and commit; double-gated by env
    register [--out PATH]  - write/print REGISTER.md (Markdown table of seeded rows)

Safety gates (apply mode only):
    - ENVIRONMENT must be 'staging'
    - ALLOW_FIXTURE_SEED must be '1'
    - --confirm must be the literal string 'I-UNDERSTAND-FIXTURE-WRITE'

Dry-run mode is permitted in any environment but still imports the
real DB stack. Run from arie-backend/ as: ``python -m fixtures.cli ...``.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import List, Optional

from fixtures.registry import APP_ID, APP_REF, SCENARIOS

REQUIRED_CONFIRM_TOKEN = "I-UNDERSTAND-FIXTURE-WRITE"


# ---------------------------------------------------------------------------
# Safety gates
# ---------------------------------------------------------------------------

def _enforce_apply_gates(confirm: Optional[str]) -> None:
    env = (os.environ.get("ENVIRONMENT") or "").lower()
    if env != "staging":
        raise SystemExit(
            f"REFUSED: apply mode requires ENVIRONMENT=staging (got '{env}')"
        )
    if os.environ.get("ALLOW_FIXTURE_SEED") != "1":
        raise SystemExit(
            "REFUSED: apply mode requires ALLOW_FIXTURE_SEED=1"
        )
    if confirm != REQUIRED_CONFIRM_TOKEN:
        raise SystemExit(
            f"REFUSED: apply mode requires --confirm '{REQUIRED_CONFIRM_TOKEN}'"
        )


# ---------------------------------------------------------------------------
# Subcommand handlers
# ---------------------------------------------------------------------------

def cmd_list(args: argparse.Namespace) -> int:
    print(f"Fixtures registry ({len(SCENARIOS)} scenarios):\n")
    for scen in SCENARIOS:
        print(f"  {scen.code}  app_id={APP_ID[scen.code]}  ref={APP_REF[scen.code]}")
        print(f"    purpose: {scen.purpose}")
        print(f"    risk:    {scen.risk_level}  country: {scen.country}  sector: {scen.sector}")
        components = []
        if scen.documents:
            components.append(f"{len(scen.documents)} docs")
        if scen.alert_spec:
            components.append("alert")
        if scen.review_spec:
            components.append("review")
        if scen.edd_spec:
            components.append("edd")
        if components:
            print(f"    components: {', '.join(components)}")
        print()
    return 0


def cmd_dry_run(args: argparse.Namespace) -> int:
    only = args.scen.split(",") if args.scen else None
    from fixtures.seeder import seed_all
    results = seed_all(dry_run=True, only=only)
    print(f"\nDRY-RUN: {len(results)} scenarios processed (all writes rolled back).\n")
    for r in results:
        print(json.dumps(r, default=str, sort_keys=True))
    return 0


def cmd_apply(args: argparse.Namespace) -> int:
    _enforce_apply_gates(args.confirm)
    only = args.scen.split(",") if args.scen else None
    from fixtures.seeder import seed_all
    results = seed_all(dry_run=False, only=only)
    print(f"\nAPPLIED: {len(results)} scenarios committed.\n")
    for r in results:
        print(json.dumps(r, default=str, sort_keys=True))
    return 0


def cmd_register(args: argparse.Namespace) -> int:
    """Render the REGISTER.md table in dry-run mode (no commit)."""
    from fixtures.seeder import seed_all
    results = seed_all(dry_run=True, only=None)
    out_lines: List[str] = []
    out_lines.append("# Fixture Register (auto-generated)\n")
    out_lines.append(
        "Generated by `python -m fixtures.cli register`. This file shows what "
        "the seeder would write. Re-generate after every registry change.\n"
    )
    out_lines.append("| Scen | App ID | App Ref | Company | Alert | Review | EDD | Docs |")
    out_lines.append("|------|--------|---------|---------|-------|--------|-----|------|")
    for r in results:
        out_lines.append(
            "| {scen} | `{app_id}` | {ref} | {company} | {alert} | {review} | {edd} | {docs} |".format(
                scen=r["scenario"],
                app_id=r["application_id"],
                ref=r["application_ref"],
                company=r["company_name"],
                alert=r.get("alert_id") or "—",
                review=r.get("review_id") or "—",
                edd=r.get("edd_id") or "—",
                docs=len(r.get("document_ids") or []),
            )
        )
    out_lines.append("")
    out_lines.append("## What each scenario proves\n")
    for r in results:
        out_lines.append(f"### {r['scenario']}")
        for p in r.get("proves") or []:
            out_lines.append(f"- {p}")
        out_lines.append("")
    text = "\n".join(out_lines)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"Wrote {args.out} ({len(results)} scenarios).")
    else:
        print(text)
    return 0


# ---------------------------------------------------------------------------
# argparse wiring
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m fixtures.cli",
        description="Onboarda staging fixture seeder (Path A, real-schema-adapted).",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="list registered scenarios").set_defaults(func=cmd_list)

    p_dry = sub.add_parser("dry-run", help="seed inside a transaction and roll back")
    p_dry.add_argument("--scen", help="comma-separated scenario codes (default: all)")
    p_dry.set_defaults(func=cmd_dry_run)

    p_app = sub.add_parser("apply", help="seed and commit (staging-only, double-gated)")
    p_app.add_argument("--confirm", required=True,
                       help=f"must be the literal '{REQUIRED_CONFIRM_TOKEN}'")
    p_app.add_argument("--scen", help="comma-separated scenario codes (default: all)")
    p_app.set_defaults(func=cmd_apply)

    p_reg = sub.add_parser("register", help="render REGISTER.md (dry-run, no commit)")
    p_reg.add_argument("--out", help="path to write to (default: stdout)")
    p_reg.set_defaults(func=cmd_register)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
