"""Branding is deployment configuration, not review input.

The governing invariant is that an identical canonical bundle under an identical
policy version yields identical findings and an identical ``review_hash``. Every
field of a finding is hashed, so any finding text derived from ``branding.BRAND``
or from an environment variable would make the hash a function of deployment
configuration rather than of the reviewed evidence. Two deployments would then
disagree on the hash for the same case, and one deployment would change its own
hashes by renaming itself.

An earlier revision of ``_draft.ADVERSE_MEDIA_COVERAGE_NOTE`` interpolated
``BRAND["platform_name"]`` into ``why_it_matters``. It read as a branding fix and
was a determinism defect. These tests exist so the same reasoning cannot be
reintroduced by a future well-intentioned branding pass.

The strongest test here rebrands the deployment *and reloads the probe package*,
so an import-time capture is caught as surely as a call-time read.
"""

from __future__ import annotations

import ast
import importlib
import os
from contextlib import contextmanager
from pathlib import Path

import pytest

import branding
from supervisor_foundation import assemble_application_bundle, canonical_bytes, run_review
from supervisor_foundation import probes as probe_package
from supervisor_foundation.policy import unconfigured_policy
from supervisor_foundation.probes import (
    PROBES,
    _draft,
    edd_divergence,
    monitoring_requirement,
    risk_resolution,
    screening_defensibility,
)
from supervisor_probe_fixtures import (
    AS_OF,
    add_memo,
    add_periodic_review,
    add_screening,
    approve,
    factor,
    risk_dimensions,
    screening_record,
    seed_application,
)

#: Reload order matters. ``screening_defensibility`` imports
#: ``ADVERSE_MEDIA_COVERAGE_NOTE`` by value, so reloading ``_draft`` alone would
#: leave the stale binding in place and the test would prove nothing.
_RELOAD_ORDER = (
    _draft,
    risk_resolution,
    edd_divergence,
    screening_defensibility,
    monitoring_requirement,
    probe_package,
)

#: A brand that shares no token with the shipped one. If any finding field is
#: branded, one of these strings surfaces in the output.
REBRAND = {
    "portal_name": "Zephyr Onboarding",
    "backoffice_name": "Zephyr Compliance Desk",
    "platform_name": "Zephyr",
    "powered_by": "Generated by Zephyr",
    "pdf_header": "Zephyr Compliance Report",
    "pdf_footer": "Generated by Zephyr",
    "system_id": "zephyr",
    "logger_name": "zephyr",
    "email_from_name": "Zephyr",
}

#: ``branding`` reads these at import. Set alongside the dict so a probe that
#: reached for the environment directly is caught by the same fixture.
REBRAND_ENV = {
    "BRAND_PORTAL_NAME": "Zephyr Onboarding",
    "BRAND_BACKOFFICE_NAME": "Zephyr Compliance Desk",
    "BRAND_WEBSITE": "https://zephyr.example",
    "BRAND_SUPPORT_EMAIL": "support@zephyr.example",
    "BRAND_EMAIL_FROM": "noreply@zephyr.example",
}

#: Product names that must never reach an officer through a finding. Checked
#: case-insensitively. ``arie`` is excluded deliberately: it is a legacy
#: technical identifier and a substring of ordinary words such as "varies".
PRODUCT_TOKENS = ("regmind", "onboarda", "zephyr")

PROBE_PACKAGE_ROOT = Path(probe_package.__file__).parent

#: Every finding field a probe authors. ``finding_id`` and the runner-stamped
#: fields are derived from these, so proving these are branding-free proves the
#: whole payload is.
AUTHORED_TEXT_FIELDS = (
    "claim",
    "why_it_matters",
    "regulatory_or_policy_basis",
    "officer_question",
    "required_action",
    "close_condition",
)


def _reload_probe_package():
    """Reload every probe module and return the freshly bound probe tuple."""
    for module in _RELOAD_ORDER:
        importlib.reload(module)
    return importlib.import_module("supervisor_foundation.probes").PROBES


@contextmanager
def rebranded():
    """Rebrand the deployment for the duration of the block, then restore it.

    Deliberately a context manager rather than a fixture, and the distinction
    is what makes the comparison tests real. A fixture applies before the test
    body, so a baseline captured inside the body would *already* be rebranded —
    and because ``importlib.reload`` mutates a module in place, the probe
    functions the test imported at collection time read the reloaded globals
    too. Both sides of the comparison would show the new brand and agree. The
    first draft of this file did exactly that, and passed against the defective
    code it was written to catch. The baseline must be taken before the block.

    Not ``monkeypatch`` either: the package has to be reloaded *after* the brand
    is put back, and monkeypatch tears down after its dependents.
    """
    original_brand = dict(branding.BRAND)
    original_env = {name: os.environ.get(name) for name in REBRAND_ENV}
    branding.BRAND.update(REBRAND)
    os.environ.update(REBRAND_ENV)
    try:
        yield _reload_probe_package()
    finally:
        branding.BRAND.clear()
        branding.BRAND.update(original_brand)
        for name, value in original_env.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value
        _reload_probe_package()


@pytest.fixture
def branded_case(db):
    """A case whose findings include the adverse-media coverage note.

    That note is the one piece of finding text that ever named the platform, so
    a case that does not produce it would make these tests vacuous. ``factor``
    scores adverse media clear and no screening report exists, which is exactly
    the state the note accompanies.
    """
    app_id = seed_application(
        db,
        risk_level="HIGH",
        final_risk_level="HIGH",
        base_risk_level="MEDIUM",
        elevation_reason_text=None,
        risk_dimensions=risk_dimensions(
            [
                factor("adverse_media", rule_score=1),
                factor("country_of_incorporation", rule_score=4,
                       resolution_status="unresolved"),
            ]
        ),
    )
    add_memo(db, app_id)
    add_periodic_review(db, app_id, status="scheduled")
    approve(db, app_id)
    return app_id


@pytest.fixture
def screened_case(db):
    """A second case, exercising the probes' screening paths.

    One case cannot reach every branch. Determinism has to hold across the
    output the whole probe set produces, not across one finding.
    """
    app_id = seed_application(db, risk_level="MEDIUM", final_risk_level="MEDIUM")
    add_memo(db, app_id)
    add_screening(db, app_id, records=[screening_record()])
    approve(db, app_id)
    return app_id


def _review(db, app_id, probes):
    bundle = assemble_application_bundle(db, app_id, as_of=AS_OF)
    return run_review(bundle, policy=unconfigured_policy(), probes=probes)


def _authored_text(review) -> list[str]:
    return [
        str(finding[field])
        for finding in review["findings"]
        for field in AUTHORED_TEXT_FIELDS
    ]


# ── The invariant ────────────────────────────────────────────────────


def test_the_coverage_note_is_produced_by_the_branded_case(branded_case, db):
    """Guard the guards: without this, every test below could pass vacuously."""
    review = _review(db, branded_case, PROBES)
    assert any(
        _draft.ADVERSE_MEDIA_COVERAGE_NOTE in str(finding["why_it_matters"])
        for finding in review["findings"]
    ), "the fixture no longer produces the adverse-media note; these tests are vacuous"


def test_rebranding_does_not_change_the_emitted_findings(
    branded_case, screened_case, db
):
    """Identical bundle, identical policy — identical findings, whatever the brand."""
    cases = (branded_case, screened_case)
    baseline = {
        app_id: canonical_bytes(_review(db, app_id, PROBES)["findings"])
        for app_id in cases
    }
    with rebranded() as probes:
        for app_id in cases:
            findings = _review(db, app_id, probes)["findings"]
            assert canonical_bytes(findings) == baseline[app_id], (
                "a finding field changed with the deployment's brand; branding "
                "is configuration, not review input"
            )


def test_rebranding_does_not_change_the_review_hash(branded_case, screened_case, db):
    """The hash identifies the evidence reviewed, not the deployment reviewing it."""
    cases = (branded_case, screened_case)
    baseline = {}
    for app_id in cases:
        review = _review(db, app_id, PROBES)
        baseline[app_id] = (
            review["review_hash"],
            review["input_bundle_hash"],
            [finding["finding_id"] for finding in review["findings"]],
        )
    with rebranded() as probes:
        for app_id in cases:
            review = _review(db, app_id, probes)
            assert (
                review["review_hash"],
                review["input_bundle_hash"],
                [finding["finding_id"] for finding in review["findings"]],
            ) == baseline[app_id], (
                "the review hash moved with the brand; an identical canonical "
                "bundle under an identical policy version must hash identically"
            )


def test_no_finding_field_names_a_product(branded_case, screened_case, db):
    """White-label safety, asserted over real output rather than over the constant."""
    for app_id in (branded_case, screened_case):
        for text in _authored_text(_review(db, app_id, PROBES)):
            lowered = text.lower()
            for token in PRODUCT_TOKENS:
                assert token not in lowered, (
                    f"a finding names the product {token!r}: {text}"
                )


def test_no_finding_field_carries_a_configured_brand_value(
    branded_case, screened_case, db
):
    """Stronger than the token list: no *configured* brand value leaks either.

    A future brand string this file has never heard of would still be caught,
    because the check reads whatever ``BRAND`` currently holds.
    """
    with rebranded() as probes:
        branded_values = [
            value.strip()
            for value in branding.BRAND.values()
            if isinstance(value, str) and len(value.strip()) > 3
        ]
        assert "Zephyr" in " ".join(branded_values), "the rebrand did not apply"
        for app_id in (branded_case, screened_case):
            for text in _authored_text(_review(db, app_id, probes)):
                for value in branded_values:
                    assert value not in text, (
                        f"a finding carries the configured brand value "
                        f"{value!r}: {text}"
                    )


# ── Static proof: the dependency cannot come back quietly ────────────


def _probe_sources():
    for path in sorted(PROBE_PACKAGE_ROOT.rglob("*.py")):
        yield path, ast.parse(path.read_text(encoding="utf-8"), filename=str(path))


def test_no_probe_module_imports_branding():
    for path, tree in _probe_sources():
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            for name in names:
                assert name.split(".")[0] != "branding", (
                    f"{path.name} imports branding; finding text is hashed and "
                    "must not depend on deployment configuration"
                )


def test_no_probe_module_reads_the_environment():
    """``os.environ``, ``os.getenv`` and a bare ``getenv`` are all rejected."""
    for path, tree in _probe_sources():
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute) and node.attr in {"environ", "getenv"}:
                pytest.fail(f"{path.name} reads the environment via os.{node.attr}")
            if isinstance(node, ast.Name) and node.id in {"getenv", "environ"}:
                pytest.fail(f"{path.name} reads the environment via {node.id}")


def test_the_coverage_note_is_a_plain_literal():
    """No f-string, no ``format``, no concatenated name — a constant string.

    A template is how the brand got in last time. The note is assembled from
    literals only, so there is nowhere for a configured value to be substituted.
    """
    source = (PROBE_PACKAGE_ROOT / "_draft.py").read_text(encoding="utf-8")
    tree = ast.parse(source)
    assigned = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Assign)
        and any(
            isinstance(target, ast.Name)
            and target.id == "ADVERSE_MEDIA_COVERAGE_NOTE"
            for target in node.targets
        )
    ]
    assert len(assigned) == 1
    for node in ast.walk(assigned[0].value):
        assert not isinstance(node, (ast.JoinedStr, ast.FormattedValue, ast.Name)), (
            "the coverage note interpolates a value; it must be literal text"
        )
    assert isinstance(_draft.ADVERSE_MEDIA_COVERAGE_NOTE, str)
    assert _draft.ADVERSE_MEDIA_COVERAGE_NOTE.strip()


def test_the_note_still_says_what_it_must():
    """Neutral wording is not an excuse for a weaker disclaimer."""
    note = _draft.ADVERSE_MEDIA_COVERAGE_NOTE.lower()
    assert "configured screening source" in note
    assert "does not establish universal" in note
