"""Semantic guards for the customer-facing RegMind brand consolidation."""

import re
import zipfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PORTAL = REPO_ROOT / "arie-portal.html"
BACKOFFICE = REPO_ROOT / "arie-backoffice.html"
MARKETING = REPO_ROOT / "index.html"
MARKETING_JSX = REPO_ROOT / "onboarda-website.jsx"
SERVER = REPO_ROOT / "arie-backend" / "server.py"

LEGACY_WORD = re.compile(r"\b(?:onboarda|arie)\b", re.IGNORECASE)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _legacy_lines(path: Path) -> list[str]:
    return [line.strip() for line in _read(path).splitlines() if LEGACY_WORD.search(line)]


def test_portal_branding_covers_key_applicant_surfaces():
    html = _read(PORTAL)
    assert "<title>RegMind Portal — Applicant Workspace</title>" in html
    assert html.count("RegMind Portal") >= 8
    for view_id in (
        "view-register",
        "view-login",
        "view-forgot-password",
        "view-reset-password",
        "view-account-security",
        "view-company-lookup",
        "view-prescreening",
        "view-onboarding",
        "view-submission-review",
        "view-docs-review",
        "view-approved",
        "view-rejected",
        "view-status-lookup",
    ):
        assert f'id="{view_id}"' in html
    assert "support@regmind.co" in html
    assert "Welcome to RegMind Portal" in html


def test_compliance_workspace_and_specialist_module_names_are_consistent():
    html = _read(BACKOFFICE)
    assert "<title>RegMind Compliance Workspace</title>" in html
    assert "<p>Compliance Workspace</p>" in html
    assert "<span>Compliance Workspace</span>" in html
    assert "RegMind AI Compliance Supervisor" in html
    assert "RegMind Monitoring" in html
    assert "RegMind Regulatory Intelligence" in html
    assert "RegMind Periodic Reviews" in html
    for view_id in (
        "view-applications",
        "view-app-detail",
        "view-screening",
        "view-edd",
        "view-periodic-review-signals",
        "view-monitoring",
        "view-reports",
        "view-settings",
        "view-audit",
        "view-reg-intel",
        "view-supervisor",
    ):
        assert f'id="{view_id}"' in html


def test_live_customer_facing_sources_have_no_unclassified_legacy_brand():
    assert _legacy_lines(MARKETING) == []
    assert _legacy_lines(PORTAL) == [
        "var common = ['password','12345678','qwerty','letmein','welcome','monkey','dragon','master','abc123','password1','onboarda'];"
    ]
    assert _legacy_lines(BACKOFFICE) == [
        "/@onboarda\\.internal/i,",
        "// arie-backend/monitoring_routing.py).",
    ]
    jsx_legacy = _legacy_lines(MARKETING_JSX)
    assert jsx_legacy == []


def test_transactional_email_and_correspondence_templates_use_regmind():
    server = _read(SERVER)
    workspace = _read(BACKOFFICE)
    assert '"RegMind Portal password reset"' in server
    assert "your RegMind Portal account" in server
    assert 'smtp_from_name = BRAND.get("email_from_name") or "RegMind"' in server
    assert "Sent via RegMind" in workspace
    assert "[Institution Name]" in workspace
    assert "Powered by RegMind" not in workspace
    assert "account with Onboarda" not in workspace


def test_generated_pdf_html_uses_regmind_brand(monkeypatch):
    import pdf_generator

    captured = {}

    class _FakeHTML:
        def __init__(self, string=None):
            captured["html"] = string

        def write_pdf(self):
            return b"%PDF-regmind"

    monkeypatch.setattr(
        pdf_generator,
        "_get_weasyprint",
        lambda: type("W", (), {"HTML": _FakeHTML})(),
    )
    rendered = pdf_generator.generate_memo_pdf(
        {
            "metadata": {
                "approval_recommendation": "REVIEW",
                "confidence_level": 0.8,
                "memo_version": "1.0",
            },
            "sections": {},
        },
        {
            "ref": "RM-BRAND-001",
            "company_name": "Customer Specific ARIE Holdings Ltd",
            "country": "MU",
            "sector": "Financial Services",
            "entity_type": "Company",
        },
    )
    assert rendered == b"%PDF-regmind"
    assert "RegMind Compliance Memorandum" in captured["html"]
    assert "Generated by RegMind" in pdf_generator.PDF_CSS
    assert "Onboarda Compliance Report" not in captured["html"]
    # Evidential/customer data is preserved even when it contains ARIE.
    assert "Customer Specific ARIE Holdings Ltd" in captured["html"]


def test_neutral_favicons_and_static_references_resolve():
    for path in (PORTAL, BACKOFFICE, MARKETING):
        html = _read(path)
        assert re.search(r'<link\s+rel="icon"\s+href="data:image/png;base64,', html)
        for attr, target in re.findall(r'\b(src|href)="([^"]+)"', html):
            if target.startswith(("http://", "https://", "mailto:", "#", "data:", "javascript:")):
                continue
            if any(marker in target for marker in ("' +", '" +', "${")):
                continue
            if not target or target.startswith("/"):
                continue
            assert (path.parent / target).exists(), f"{path.name} has missing {attr} resource: {target}"


def test_active_compliance_resource_branding_and_legacy_record_compatibility():
    import server

    expected = {
        "regulatory-compliance-report": (
            "RegMind Regulatory Compliance Report",
            "RegMind_Regulatory_Compliance_Report.docx",
        ),
        "sample-compliance-memo": (
            "RegMind Sample Compliance Memo",
            "RegMind_Sample_Compliance_Memo.pdf",
        ),
    }
    for slug, (title, file_name) in expected.items():
        path = REPO_ROOT / "docs" / "compliance" / file_name
        assert path.is_file()
        override = server._SYSTEM_COMPLIANCE_RESOURCE_PRESENTATION[slug]
        assert override["title"] == title
        assert override["file_name"] == file_name
        assert (REPO_ROOT / override["file_path"]).is_file()

        presented = server._present_compliance_resource({
            "slug": slug,
            "title": "Onboarda legacy persisted title",
            "file_name": "Onboarda_legacy_persisted_file.pdf",
        })
        assert presented["title"] == title
        assert presented["file_name"] == file_name

    assert not (REPO_ROOT / "docs" / "compliance" / "Onboarda_Regulatory_Compliance_Report.docx").exists()
    assert not (REPO_ROOT / "docs" / "compliance" / "Onboarda_Sample_Compliance_Memo.pdf").exists()


def test_historical_customer_specific_arie_evidence_is_not_rewritten():
    deck = REPO_ROOT / "decks" / "Onboarda_Marketing_Deck_v2.pptx"
    with zipfile.ZipFile(deck) as archive:
        slide_xml = "\n".join(
            archive.read(name).decode("utf-8")
            for name in archive.namelist()
            if name.startswith("ppt/slides/slide") and name.endswith(".xml")
        )
    assert "ARIE Finance" in slide_xml
    assert "Regulated Partner" in slide_xml
