"""
RegMind Platform — Centralised Branding Configuration
Config-driven branding for the applicant portal, compliance workspace, email,
and generated output.

Usage:
    from branding import BRAND

    print(BRAND["portal_name"])       # "RegMind Portal"
    print(BRAND["backoffice_name"])   # "RegMind Compliance Workspace"
    print(BRAND["pdf_header"])        # "RegMind Compliance Memorandum"
    print(BRAND["pdf_footer"])        # "Generated by RegMind"

All tenant-independent customer-facing surfaces use "RegMind".
Institution-specific legal identity remains runtime/tenant data.
System-level logs and metrics use "regmind" as the technical identifier.
"""

import os

# ═══════════════════════════════════════════════════════════
# BRAND CONFIGURATION — Single source of truth
# ═══════════════════════════════════════════════════════════

BRAND = {
    # ── Client-facing (external) ──
    "portal_name": os.environ.get("BRAND_PORTAL_NAME", "RegMind Portal"),
    "portal_tagline": os.environ.get("BRAND_PORTAL_TAGLINE", "Compliance. Automated. Explained."),
    "portal_description": "AI-powered compliance onboarding platform for regulated institutions",

    # ── Back office (internal) ──
    "backoffice_name": os.environ.get("BRAND_BACKOFFICE_NAME", "RegMind Compliance Workspace"),
    "backoffice_tagline": "Intelligent compliance operations",

    # ── Combined / system ──
    "platform_name": "RegMind",
    "powered_by": "Generated by RegMind",
    "company_legal": os.environ.get("BRAND_COMPANY_LEGAL_NAME", "Your Financial Institution"),
    "copyright": "\u00a9 2026 RegMind. All rights reserved.",
    "support_email": os.environ.get("BRAND_SUPPORT_EMAIL", "support@regmind.co"),
    "website": os.environ.get("BRAND_WEBSITE", "https://regmind.co"),

    # ── PDF output ──
    "pdf_header": "RegMind Compliance Memorandum",
    "pdf_footer": "Generated by RegMind",
    "pdf_classification": "CONFIDENTIAL",
    "pdf_watermark": None,  # Set to string to enable watermark

    # ── Technical identifiers (logs, metrics, cookies) ──
    "system_id": "regmind",
    "logger_name": "regmind",
    "cookie_prefix": "arie",  # Keep existing cookie name for backward compatibility
    "metric_prefix": "arie",  # Keep existing metric prefix for Prometheus continuity

    # ── Email ──
    "email_from_name": "RegMind",
    "email_from_address": os.environ.get("BRAND_EMAIL_FROM", "noreply@regmind.co"),
}


# ═══════════════════════════════════════════════════════════
# CONVENIENCE ACCESSORS
# ═══════════════════════════════════════════════════════════

def portal_name() -> str:
    """Client-facing product name."""
    return BRAND["portal_name"]

def backoffice_name() -> str:
    """Internal compliance officer product name."""
    return BRAND["backoffice_name"]

def powered_by() -> str:
    """Attribution line for footers and generated content."""
    return BRAND["powered_by"]

def pdf_header() -> str:
    """Title for PDF compliance report header."""
    return BRAND["pdf_header"]

def pdf_footer() -> str:
    """Footer text for PDF compliance reports."""
    return BRAND["pdf_footer"]

def system_id() -> str:
    """Technical system identifier for logs and metrics."""
    return BRAND["system_id"]


# ═══════════════════════════════════════════════════════════
# HUMAN-READABLE STATUS LABELS
# ═══════════════════════════════════════════════════════════
# Maps internal application status codes to clear, non-technical
# language suitable for clients, compliance officers, and audit logs.

STATUS_LABELS = {
    "draft":                     "Application Started",
    "submitted":                 "Application Submitted",
    "prescreening_submitted":    "Pre-Screening in Progress",
    "pricing_review":            "Pricing Under Review",
    "pricing_accepted":          "Pricing Accepted",
    "pre_approval_review":       "Pre-Approval Under Review",
    "pre_approved":              "Pre-Approved",
    "kyc_documents":             "KYC Documents Required",
    "kyc_submitted":             "KYC Documents Submitted",
    "compliance_review":         "Compliance Review in Progress",
    "submitted_to_compliance":   "Submitted to Compliance",
    "in_review":                 "Verification Ongoing",
    "under_review":              "Under Compliance Review",
    "edd_required":              "Enhanced Due Diligence Required",
    "approved":                  "Approved – Ready for Activation",
    "rejected":                  "Application Declined",
    "rmi_sent":                  "Further Information Requested",
    "withdrawn":                 "Application Withdrawn",
}


RISK_LABELS = {
    "LOW": "Low Risk",
    "MEDIUM": "Medium Risk",
    "HIGH": "High Risk",
    "VERY_HIGH": "Very High Risk",
}


def get_status_label(status):
    """Return a human-readable label for an application status code.

    Falls back to a title-cased version of the status if no mapping exists.
    """
    return STATUS_LABELS.get(status, status.replace("_", " ").title() if status else "Unknown")


def get_risk_label(risk_level):
    """Return the canonical display label for a risk level."""
    key = str(risk_level or "").strip().upper()
    if not key:
        return "Unknown"
    return RISK_LABELS.get(key, key.replace("_", " ").title())
