"""
ARIE Finance — Validation Engine: 15-rule Memo Quality Auditor
Extracted from server.py during Sprint 2 monolith decomposition.

Provides:
    - validate_compliance_memo() — 15-point rules-based memo validation
    - pre_validate_application() — Pre-flight field validation
    - generate_fallback_memo() — Safe fallback when AI pipeline fails
"""
import logging
from datetime import datetime

logger = logging.getLogger("arie")

def generate_fallback_memo(application=None):
    """
    Return a safe, structured fallback memo when AI generation fails.
    Used during demos or when the Claude API is unavailable.
    The memo is intentionally conservative (REJECT recommendation).
    """
    app = application or {}
    company = app.get("company_name", "Unknown Company")
    country = app.get("country", "Unknown")
    sector = app.get("sector", "Unknown")

    return {
        "sections": {
            "executive_summary": {"content": f"Compliance memo for {company} could not be generated by the AI pipeline. This is a fallback memo requiring manual review."},
            "client_overview": {"content": f"{company}, {sector} sector, domiciled in {country}."},
            "ownership_and_control": {"content": "Ownership data not analysed — fallback memo.", "structure_complexity": "Unknown", "control_statement": "Not assessed — requires manual review."},
            "risk_assessment": {
                "content": "Risk assessment not performed — fallback memo.",
                "sub_sections": {
                    "jurisdiction_risk": {"rating": "MEDIUM", "content": f"{country} — not assessed"},
                    "business_risk": {"rating": "MEDIUM", "content": f"{sector} — not assessed"},
                    "transaction_risk": {"rating": "MEDIUM", "content": "Not assessed"},
                    "ownership_risk": {"rating": "MEDIUM", "content": "Not assessed"},
                    "financial_crime_risk": {"rating": "MEDIUM", "content": "Not assessed"}
                }
            },
            "screening_results": {"content": "Screening not completed — fallback memo. Manual screening required."},
            "document_verification": {"content": "Document verification not completed — requires manual review."},
            "ai_explainability": {"content": "AI pipeline failed or was unavailable. Fallback memo generated.", "risk_increasing_factors": ["AI pipeline failure"], "risk_decreasing_factors": []},
            "red_flags_and_mitigants": {"red_flags": ["AI-generated memo unavailable"], "mitigants": ["Fallback memo generated for manual review"]},
            "compliance_decision": {"decision": "REJECT", "content": "Automatic REJECT — AI pipeline unavailable. Requires manual compliance review."},
            "ongoing_monitoring": {"content": "Enhanced monitoring required pending manual review."},
            "audit_and_governance": {"content": "Fallback memo generated. Full audit trail maintained."}
        },
        "metadata": {
            "risk_rating": "MEDIUM",
            "risk_score": 50,
            "approval_recommendation": "REJECT",
            "confidence_level": 0.0,
            "is_fallback": True,
            "fallback_reason": "AI pipeline failure",
            "original_risk_level": app.get("risk_level", "MEDIUM"),
            "aggregated_risk": "MEDIUM",
            "rule_engine": {"violations": [], "enforcements": [], "engine_status": "SKIPPED"}
        }
    }


def pre_validate_application(application_data):
    """
    Validate required fields BEFORE entering the AI pipeline.
    Returns (is_valid, errors) — fail early with structured errors.
    """
    errors = []
    if application_data is None:
        return False, [{"field": "application", "error": "Application data is None or empty"}]

    required = ["company_name", "country", "sector", "entity_type"]
    for field in required:
        val = application_data.get(field)
        if not val or (isinstance(val, str) and not val.strip()):
            errors.append({"field": field, "error": f"Required field '{field}' is missing or empty"})

    # Validate country is a string
    country = application_data.get("country", "")
    if country and not isinstance(country, str):
        errors.append({"field": "country", "error": f"Country must be a string, got {type(country).__name__}"})

    return len(errors) == 0, errors


# ══════════════════════════════════════════════════════════
# MEMO VALIDATION ENGINE (Step 5b)
# ══════════════════════════════════════════════════════════

def validate_compliance_memo(memo_data):
    """
    Rules-based Memo Validation Engine.
    Audits a generated compliance memo for quality, consistency, contradictions, and completeness.

    Returns:
        {
            "validation_status": "pass" | "pass_with_fixes" | "fail",
            "quality_score": float (0-10),
            "issues": [{"category": str, "severity": "critical"|"warning"|"info", "description": str, "fix": str}],
            "summary": str
        }
    """
    issues = []
    scores = {}

    sections = memo_data.get("sections") or {}
    metadata = memo_data.get("metadata") or {}

    # Defensive: ensure sub-dicts are dicts not None
    for key in list(sections.keys()):
        if sections[key] is None:
            sections[key] = {}

    # ── 1. STRUCTURAL COMPLETENESS (weight: 1.5) ──
    required_sections = [
        "executive_summary", "client_overview", "ownership_and_control",
        "risk_assessment", "screening_results", "document_verification",
        "ai_explainability", "red_flags_and_mitigants", "compliance_decision",
        "ongoing_monitoring", "audit_and_governance"
    ]
    missing_sections = [s for s in required_sections if s not in sections]
    if missing_sections:
        issues.append({"category": "structure", "severity": "critical", "description": f"Missing required sections: {', '.join(missing_sections)}", "fix": "Regenerate memo with all 11 mandatory sections."})
        scores["structure"] = max(0, 1.0 - len(missing_sections) * 0.2)
    else:
        scores["structure"] = 1.5

    # ── 2. RISK ASSESSMENT CONSISTENCY (weight: 2.0) ──
    risk_section = sections.get("risk_assessment", {})
    sub_sections = risk_section.get("sub_sections") or {}
    overall_rating = metadata.get("risk_rating", "")
    overall_score = metadata.get("risk_score", 0)

    RISK_RANK = {"LOW": 1, "MEDIUM": 2, "HIGH": 3, "VERY_HIGH": 4}
    sub_ratings = []
    for key in ["jurisdiction_risk", "business_risk", "transaction_risk", "ownership_risk", "financial_crime_risk"]:
        sub = sub_sections.get(key, {})
        if sub.get("rating"):
            sub_ratings.append(RISK_RANK.get(sub["rating"], 2))
        else:
            issues.append({"category": "risk_consistency", "severity": "warning", "description": f"Risk sub-section '{key}' missing rating.", "fix": f"Add explicit risk rating to {key}."})

    if sub_ratings:
        avg_sub_risk = sum(sub_ratings) / len(sub_ratings)
        overall_rank = RISK_RANK.get(overall_rating, 2)

        # Check if overall risk diverges significantly from sub-ratings
        if abs(overall_rank - avg_sub_risk) > 1.5:
            issues.append({"category": "risk_consistency", "severity": "critical", "description": f"Overall risk rating ({overall_rating}) significantly diverges from average sub-section risk ({avg_sub_risk:.1f}/4). This contradiction would not withstand regulatory scrutiny.", "fix": "Reconcile overall risk rating with individual risk dimension assessments."})
            scores["risk_consistency"] = 0.5
        elif abs(overall_rank - avg_sub_risk) > 0.8:
            issues.append({"category": "risk_consistency", "severity": "warning", "description": f"Overall risk rating ({overall_rating}) moderately diverges from sub-section ratings. Ensure the memo explains why.", "fix": "Add explicit justification for the overall rating in the executive summary."})
            scores["risk_consistency"] = 1.5
        else:
            scores["risk_consistency"] = 2.0
    else:
        scores["risk_consistency"] = 0

    # ── 3. DECISION ALIGNMENT (weight: 2.0) ──
    decision_section = sections.get("compliance_decision", {})
    decision = decision_section.get("decision", metadata.get("approval_recommendation", ""))

    if overall_rating == "LOW" and decision in ("REVIEW", "REJECT"):
        issues.append({"category": "decision_alignment", "severity": "critical", "description": f"Low-risk entity ({overall_score}/100) has decision '{decision}'. This is contradictory.", "fix": "Align decision with risk assessment — LOW risk should lead to APPROVE or APPROVE_WITH_CONDITIONS."})
        scores["decision"] = 0
    elif overall_rating in ("HIGH", "VERY_HIGH") and decision == "APPROVE":
        issues.append({"category": "decision_alignment", "severity": "critical", "description": f"High-risk entity ({overall_score}/100) approved without conditions. This would fail regulatory review.", "fix": "High/Very High risk requires APPROVE_WITH_CONDITIONS, REVIEW, or REJECT."})
        scores["decision"] = 0
    elif overall_rating == "MEDIUM" and decision == "REJECT":
        issues.append({"category": "decision_alignment", "severity": "warning", "description": "Medium-risk entity rejected. Ensure rejection rationale is clearly documented.", "fix": "Add detailed rejection rationale or downgrade to REVIEW."})
        scores["decision"] = 1.0
    else:
        scores["decision"] = 2.0

    # ── 4. OWNERSHIP ANALYSIS QUALITY (weight: 1.0) ──
    ownership = sections.get("ownership_and_control", {})
    own_content = ownership.get("content", "")
    has_complexity = bool(ownership.get("structure_complexity"))
    has_control = bool(ownership.get("control_statement"))
    has_pct = "%" in own_content or "ownership" in own_content.lower()

    own_score = 0
    if has_complexity:
        own_score += 0.3
    else:
        issues.append({"category": "ownership", "severity": "warning", "description": "Structure complexity rating missing (Simple/Layered/Complex).", "fix": "Add structure_complexity field to ownership section."})
    if has_control:
        own_score += 0.4
    else:
        issues.append({"category": "ownership", "severity": "critical", "description": "Control statement missing — who exercises effective control is not identified.", "fix": "Add control_statement identifying the person exercising effective control and basis for determination."})
    if has_pct:
        own_score += 0.3
    else:
        issues.append({"category": "ownership", "severity": "critical", "description": "UBO ownership percentages not stated in ownership section.", "fix": "Include % ownership for every UBO, or explicitly flag as 'Information not provided'."})
    scores["ownership"] = own_score

    # ── 5. SCREENING DEFENSIBILITY (weight: 1.0) ──
    screening = sections.get("screening_results", {})
    screen_content = screening.get("content", "")
    screen_score = 0

    if "simulated" in screen_content.lower():
        issues.append({"category": "screening", "severity": "critical", "description": "Screening results reference 'simulated' data. This is not defensible.", "fix": "Remove 'simulated' language. Reference actual screening provider or state 'screening pending'."})
    else:
        screen_score += 0.4

    if "false positive" in screen_content.lower() or "true positive" in screen_content.lower():
        screen_score += 0.3
    else:
        if any(word in screen_content.lower() for word in ["match", "hit", "pep"]):
            issues.append({"category": "screening", "severity": "warning", "description": "Screening matches found but no false positive analysis included.", "fix": "Add false positive determination for each screening match."})

    if any(provider in screen_content for provider in ["OpenSanctions", "Sumsub", "World-Check", "Dow Jones", "Refinitiv", "Onboarda screening engine"]):
        screen_score += 0.3
    else:
        issues.append({"category": "screening", "severity": "info", "description": "Screening provider not explicitly named.", "fix": "Reference the screening data source for audit defensibility."})

    scores["screening"] = screen_score

    # ── 6. DOCUMENT VERIFICATION QUALITY (weight: 0.5) ──
    doc_section = sections.get("document_verification", {})
    doc_content = doc_section.get("content", "")

    if "consistent" in doc_content.lower() or "authentic" in doc_content.lower() or "discrepanc" in doc_content.lower():
        scores["documents"] = 0.5
    elif "verified" in doc_content.lower():
        scores["documents"] = 0.3
        issues.append({"category": "documents", "severity": "info", "description": "Documents listed as verified but no consistency assessment with other data.", "fix": "For each document, state consistency with other submitted data and any anomalies."})
    else:
        scores["documents"] = 0.1
        issues.append({"category": "documents", "severity": "warning", "description": "Document verification section lacks substantive assessment.", "fix": "Add per-document verification status, consistency checks, and anomaly notes."})

    # ── 7. RED FLAGS & MITIGANTS (weight: 1.0) ──
    rf_section = sections.get("red_flags_and_mitigants", {})
    red_flags = rf_section.get("red_flags", [])
    mitigants = rf_section.get("mitigants", [])
    rf_score = 0

    if len(red_flags) >= 2:
        rf_score += 0.4
    elif len(red_flags) == 1:
        rf_score += 0.2
        issues.append({"category": "red_flags", "severity": "warning", "description": f"Only {len(red_flags)} red flag(s) identified. Minimum 2 expected for defensibility.", "fix": "Add additional contextual red flags (e.g., limited trading history, data gaps, sector exposure)."})
    else:
        issues.append({"category": "red_flags", "severity": "critical", "description": "No red flags identified. Every onboarding must document at least residual risks.", "fix": "Add minimum 2 red flags. Even low-risk cases have risks (limited history, data gaps)."})

    if len(mitigants) >= 2:
        rf_score += 0.4
    elif len(mitigants) == 1:
        rf_score += 0.2
        issues.append({"category": "red_flags", "severity": "info", "description": "Only 1 mitigant listed. Consider adding more for balance.", "fix": "Add corresponding mitigants for each red flag."})
    else:
        issues.append({"category": "red_flags", "severity": "warning", "description": "No mitigants listed alongside red flags.", "fix": "Each red flag should have a corresponding mitigant."})

    # Check red flags are substantive (not just one-liners)
    thin_flags = [f for f in red_flags if len(f) < 30]
    if thin_flags:
        rf_score -= 0.1 * len(thin_flags)
        issues.append({"category": "red_flags", "severity": "info", "description": f"{len(thin_flags)} red flag(s) are too brief to be defensible.", "fix": "Expand red flags with explanation of WHY each is a concern."})

    scores["red_flags"] = max(0, rf_score)

    # ── 8. CONFIDENCE & EXPLAINABILITY (weight: 0.5) ──
    ai_section = sections.get("ai_explainability", {})
    ai_content = ai_section.get("content", "")
    confidence = metadata.get("confidence_level", 0)
    conf_score = 0

    if confidence and confidence > 0:
        conf_score += 0.2
    else:
        issues.append({"category": "explainability", "severity": "warning", "description": "No confidence score in metadata.", "fix": "Include confidence_level (0-1) in memo metadata."})

    if "weight" in ai_content.lower() or "factor" in ai_content.lower():
        conf_score += 0.2
    else:
        issues.append({"category": "explainability", "severity": "warning", "description": "AI explainability section lacks factor-level weights.", "fix": "Include top risk-increasing and risk-decreasing factors with weights."})

    if "pathway" in ai_content.lower() or "pipeline" in ai_content.lower() or "agent" in ai_content.lower():
        conf_score += 0.1

    # Low confidence should trigger review
    if confidence and confidence < 0.7 and decision == "APPROVE":
        issues.append({"category": "explainability", "severity": "warning", "description": f"Low model confidence ({confidence:.0%}) but APPROVE decision. Consider conditions or review.", "fix": "Link low confidence to enhanced monitoring conditions or escalate to REVIEW."})

    scores["explainability"] = conf_score

    # ── 9. FACTOR CLASSIFICATION CORRECTNESS (weight: 0.5) ──
    ai_section_factors = sections.get("ai_explainability", {})
    increasing = ai_section_factors.get("risk_increasing_factors", [])
    decreasing = ai_section_factors.get("risk_decreasing_factors", [])
    factor_score = 0

    # Check that risk-decreasing items are not in risk-increasing list
    misclassified = []
    decrease_keywords = ["no pep", "low jurisdictional", "clean sanctions", "low sector", "full documentation", "low inherent"]
    for f in increasing:
        f_lower = f.lower() if isinstance(f, str) else ""
        if any(kw in f_lower for kw in decrease_keywords):
            misclassified.append(f)
    if misclassified:
        issues.append({"category": "factor_classification", "severity": "critical", "description": f"Risk-decreasing items incorrectly classified as risk-increasing: {'; '.join(misclassified[:2])}", "fix": "Move risk-decreasing items to the risk_decreasing_factors list."})
    else:
        factor_score += 0.3

    # Check that factors exist
    if increasing:
        factor_score += 0.1
    else:
        issues.append({"category": "factor_classification", "severity": "warning", "description": "No risk-increasing factors listed. Every case has at least residual risk factors.", "fix": "Add risk-increasing factors (e.g., limited trading history, data gaps)."})
    if decreasing:
        factor_score += 0.1
    else:
        issues.append({"category": "factor_classification", "severity": "warning", "description": "No risk-decreasing factors listed.", "fix": "Add risk-decreasing factors (e.g., clean screening, verified ownership)."})
    scores["factor_classification"] = factor_score

    # ── 10. OWNERSHIP RISK CORRECTNESS (weight: 0.5) ──
    own_risk_section = sub_sections.get("ownership_risk", {})
    own_risk_rating = own_risk_section.get("rating", "")
    own_risk_content = own_risk_section.get("content", "")
    own_risk_score = 0

    # Check if ownership risk is LOW but there are signs it shouldn't be
    if own_risk_rating == "LOW":
        has_missing_pct = "not provided" in own_risk_content.lower() or "missing" in own_risk_content.lower() or "incomplete" in own_risk_content.lower()
        has_no_ubo = "no ubo" in own_risk_content.lower() or "could not be verified" in own_risk_content.lower()
        has_complex = "complex" in own_risk_content.lower()
        if has_missing_pct or has_no_ubo or has_complex:
            issues.append({"category": "ownership_risk", "severity": "critical", "description": f"Ownership risk rated LOW but content indicates data gaps or complexity: {'missing percentages' if has_missing_pct else ''}{'no UBO data' if has_no_ubo else ''}{'complex structure' if has_complex else ''}", "fix": "Ownership risk must not remain LOW when ownership percentages are missing, UBOs are unidentified, or structure is complex."})
        else:
            own_risk_score += 0.3
    else:
        own_risk_score += 0.3

    # Check justification is present
    if "based on" in own_risk_content.lower() or "rating" in own_risk_content.lower() or "justification" in own_risk_content.lower():
        own_risk_score += 0.2
    else:
        issues.append({"category": "ownership_risk", "severity": "warning", "description": "Ownership risk rating lacks explicit justification.", "fix": "Add clear justification explaining why ownership risk is rated as stated."})
    scores["ownership_risk"] = own_risk_score

    # ── 11. CONFIDENCE-TO-DECISION LINKAGE (weight: 0.5) ──
    conf_level = metadata.get("confidence_level", 0)
    low_conf_flag = metadata.get("low_confidence_flag", False)
    memo_decision = metadata.get("approval_recommendation", "")
    conf_decision_score = 0

    if conf_level and conf_level < 0.7 and memo_decision == "APPROVE":
        issues.append({"category": "confidence_decision", "severity": "critical", "description": f"Model confidence is {conf_level:.0%} (below 70% threshold) but decision is unconditional APPROVE. Low confidence should trigger conditions or review.", "fix": "When model confidence < 70%, decision should be APPROVE_WITH_CONDITIONS or REVIEW, not unconditional APPROVE."})
    elif conf_level and conf_level < 0.7 and memo_decision == "APPROVE_WITH_CONDITIONS":
        conf_decision_score += 0.3
        # Check if conditions mention confidence
        exec_content = sections.get("executive_summary", {}).get("content", "")
        if "confidence" in exec_content.lower():
            conf_decision_score += 0.2
        else:
            issues.append({"category": "confidence_decision", "severity": "info", "description": "Low confidence noted but not explicitly referenced in executive summary.", "fix": "Reference reduced model confidence in the executive summary and its impact on the recommendation."})
    else:
        conf_decision_score += 0.5
    scores["confidence_decision"] = conf_decision_score

    # ── 12. DOCUMENT ADEQUACY IMPACT (weight: 0.5) ──
    doc_adequacy_score = 0
    doc_content_full = sections.get("document_verification", {}).get("content", "")

    if "professional judgement" in doc_content_full.lower() or "impact assessment" in doc_content_full.lower() or "assurance level" in doc_content_full.lower():
        doc_adequacy_score += 0.3
    else:
        issues.append({"category": "doc_adequacy", "severity": "info", "description": "Document verification lacks professional judgement statement on adequacy impact.", "fix": "Add professional judgement on how documentation gaps affect overall assurance level."})

    # Check if outstanding docs are reflected in decision conditions
    if "outstanding" in doc_content_full.lower() or "pending" in doc_content_full.lower():
        decision_content = sections.get("compliance_decision", {}).get("content", "")
        if "document" in decision_content.lower() or "outstanding" in decision_content.lower():
            doc_adequacy_score += 0.2
        else:
            issues.append({"category": "doc_adequacy", "severity": "warning", "description": "Outstanding documents mentioned in verification but not reflected in compliance decision conditions.", "fix": "Ensure outstanding documents are listed as conditions in the compliance decision."})
    else:
        doc_adequacy_score += 0.2
    scores["doc_adequacy"] = doc_adequacy_score

    # ── 13. MISSING DATA HANDLING (weight: 0.5) ──
    all_content = " ".join([
        (sections.get(k) or {}).get("content") or "" for k in required_sections
        if k != "risk_assessment"
    ])
    data_gap_score = 0

    if "information not provided" in all_content.lower():
        data_gap_score += 0.3  # Good — missing data is flagged
        if "data gap" in all_content.lower() or "elevates" in all_content.lower() or "prevents" in all_content.lower():
            data_gap_score += 0.2  # Excellent — impact is assessed
        else:
            issues.append({"category": "data_gaps", "severity": "info", "description": "Missing data is flagged but impact on risk is not assessed.", "fix": "For each 'Information not provided', add impact statement."})
    else:
        # No missing data flagged — could be fine if data is complete, or a problem if it's not
        data_gap_score += 0.3
    scores["data_gaps"] = data_gap_score

    # ── 14. RULE ENGINE COMPLIANCE (weight: 1.0) ──
    rule_engine = metadata.get("rule_engine", {})
    rule_eng_violations = rule_engine.get("violations", [])
    rule_eng_enforcements = rule_engine.get("enforcements", [])
    rule_engine_score = 0

    if rule_eng_violations:
        critical_rv = [v for v in rule_eng_violations if v.get("severity") == "high" or v.get("severity") == "critical"]
        if critical_rv:
            issues.append({
                "category": "rule_engine",
                "severity": "critical",
                "description": (
                    "Pre-generation Rule Engine detected " + str(len(critical_rv)) + " high/critical violation(s): "
                    + "; ".join([v.get("detail", "")[:60] for v in critical_rv[:3]])
                ),
                "fix": "Rule violations must be resolved. Factor misclassifications should be corrected before memo approval."
            })
        else:
            issues.append({
                "category": "rule_engine",
                "severity": "warning",
                "description": "Rule Engine detected " + str(len(rule_eng_violations)) + " minor violation(s).",
                "fix": "Review rule violations and resolve where possible."
            })
            rule_engine_score += 0.5
    else:
        rule_engine_score += 0.7

    if rule_eng_enforcements:
        # Enforcements are corrections the Rule Engine made — document them
        issues.append({
            "category": "rule_engine",
            "severity": "info",
            "description": (
                "Rule Engine applied " + str(len(rule_eng_enforcements)) + " enforcement(s): "
                + ", ".join([e.get("rule", "") for e in rule_eng_enforcements])
            ),
            "fix": "No action required — these were automatically corrected by the Rule Engine."
        })
        rule_engine_score += 0.3
    else:
        rule_engine_score += 0.3

    scores["rule_engine"] = rule_engine_score

    # ── 15. DECISION-RISK ENFORCEMENT CHECK (weight: 0.5) ──
    # Verify the Rule Engine's enforcement was respected in the final decision
    decision_enforcement_score = 0
    for enforcement in rule_eng_enforcements:
        if enforcement.get("rule") == "CONFIDENCE_FLOOR":
            # Verify decision was actually changed
            if memo_decision == "APPROVE":
                issues.append({
                    "category": "rule_enforcement_check",
                    "severity": "critical",
                    "description": "CONFIDENCE_FLOOR enforcement was applied but final decision is still APPROVE.",
                    "fix": "Decision must reflect confidence floor enforcement — should be APPROVE_WITH_CONDITIONS or higher."
                })
            else:
                decision_enforcement_score += 0.25
        elif enforcement.get("rule") in ("OWNERSHIP_FLOOR", "BUSINESS_RISK_FLOOR", "MULTI_GAP_ESCALATION"):
            decision_enforcement_score += 0.25

    if not rule_eng_enforcements:
        decision_enforcement_score = 0.5  # No enforcements needed — clean
    scores["rule_enforcement_check"] = min(decision_enforcement_score, 0.5)

    # ── COMPUTE FINAL SCORE ──
    total = sum(scores.values())
    max_possible = 13.5  # Updated: 13 original categories + 2 new rule engine categories
    quality_score = round(min(total / max_possible * 10, 10), 1)

    # Determine status
    critical_issues = [i for i in issues if i["severity"] == "critical"]
    warning_issues = [i for i in issues if i["severity"] == "warning"]

    if len(critical_issues) >= 2 or quality_score < 4.0:
        validation_status = "fail"
    elif critical_issues or quality_score < 6.5:
        validation_status = "pass_with_fixes"
    elif len(warning_issues) >= 3 and quality_score < 7.5:
        validation_status = "pass_with_fixes"
    else:
        validation_status = "pass"

    summary_parts = []
    if critical_issues:
        summary_parts.append(f"{len(critical_issues)} critical issue(s) requiring immediate attention")
    if warning_issues:
        summary_parts.append(f"{len(warning_issues)} warning(s)")
    if not issues:
        summary_parts.append("No issues identified — memo meets gold-standard requirements")

    # Map internal score keys → frontend-expected category names for display.
    # Keep scores_breakdown for backend consumers; add category_scores for the UI.
    _CATEGORY_KEY_MAP = {
        "structure": "structural_completeness",
        "risk_consistency": "risk_consistency",
        "decision": "decision_alignment",
        "ownership": "ownership_quality",
        "screening": "screening_defensibility",
        "documents": "document_verification",
        "red_flags": "red_flags_mitigants",
        "explainability": "confidence_explainability",
        "data_gaps": "missing_data_handling",
        # Additional granular keys — pass through unchanged
        "factor_classification": "factor_classification",
        "ownership_risk": "ownership_risk",
        "confidence_decision": "confidence_decision",
        "doc_adequacy": "doc_adequacy",
        "rule_engine": "rule_engine",
        "rule_enforcement_check": "rule_enforcement_check",
    }
    category_scores = {_CATEGORY_KEY_MAP.get(k, k): v for k, v in scores.items()}

    return {
        "validation_status": validation_status,
        "quality_score": quality_score,
        "issues": issues,
        "scores_breakdown": scores,
        "category_scores": category_scores,
        "summary": ". ".join(summary_parts) + ".",
        "total_issues": len(issues),
        "critical_count": len(critical_issues),
        "warning_count": len(warning_issues),
        "validated_at": datetime.now().isoformat()
    }
